### ISSUE TITLE
Shape removal doesn't seem to be working

### ISSUE THREAD

**Issue by jbrower** [vrld/HC#27]
I'm trying to remove some shapes.  I create the shape using

self.collShape = Collider:addCircle(self.x, self.y, self.radius)

and can add it to collision groups by doing

 Collider:addToGroup("enemies", self.collShape)

The problem is when I want to remove the collision shape I try to do

Collider:remove(self.collShape)

and it doesn't seem to have any effect.

Am I doing something wrong?

**Comment by vrld** [comment]
Not relevant anymore
