### ISSUE TITLE
intersectsRay not working for points?

### ISSUE THREAD

**Issue by lzubiaur** [vrld/HC#38]
Hi, I can't get intersectsRay to work for point shapes. In the code below, I get false for the circle (correct) but returns true for the point.

``` lua
 local hc = HC(100,nil,nil) 

 local circle = hc:addCircle(200,100,10)
 local i,t = circle:intersectsRay(0,0,10,0)
 print(i,t) -- Print false inf

 local point = hc:addPoint(200,100)
 local i,t = point:intersectsRay(0,0,10,0)
 print(i,t) -- Print true 20
```

Thank you in advance, 
Laurent

**Comment by buckle2000** [comment]
What were you thinking?
A point has no volume by definition. You should use a small circle instead.
