### ISSUE TITLE
Support Love version 0.10+ (love.graphics.point was removed in 0.10)

### ISSUE THREAD

**Issue by zzzaim** [vrld/HC#64]
https://github.com/vrld/HC/blob/d2b7f0d96242be3fec520b7ed8e59982d4deb399/shapes.lua#L425

The function `love.graphics.point` was removed in Love 0.10, and replaced by `points` (plural).

See: https://love2d.org/wiki/love.graphics.point

Thanks.

**Comment by vrld** [comment]
Closed with a9261b83fa17b01e1ab5e410c896bc5c403485ee
